name: BunJS Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geldata/setup-gel@v1
      - run: gel --version

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: "https://npm.pkg.github.com/"

      - name: Install dependencies
        run: bun install

      - name: Generate EdgeQL-JS
        run: bunx @gel/generate edgeql-js

      - name: Run tests
        run: bun test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: "https://npm.pkg.github.com/"
      - run: bun install
      - run: bun publish
        env:
          BUN_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
